### PR TITLE
fix: go-redis use redis.Cmdable interface

### PR DESCRIPTION
**Pull request by lpxxn**
replace `redis.Client` with `redis.Cmdable` interface     

https://github.com/go-redsync/redsync/issues/52

### CODE REVIEW

**Comment by aranda-adapptor** [comment]
I'd like this feature too, thanks for implementing @lpxxn . I was able to test by replacing redsync with your branch:

```
replace github.com/go-redsync/redsync/v4 => github.com/lpxxn/redsync/v4 v4.0.4-0.20201102140619-1338ac61c806
```

**Comment by darful** [comment]
Hi!  I ran into a similar issue and believe a better solution is to use `go-redis's` `UniversalClient` interface instead of `Cmdable`.  See this [PR](https://github.com/go-redsync/redsync/pull/63).

**Comment by vincenthcui** [comment]
thanks for implementing, this feature is used for me.
@darful UniversalClient is also good solution, can you speak in detail why `UniversalClient` is better than a `Cmdable` interface? Usually, golang like interface more than a specific implement.

**Comment by darful** [comment]
> thanks for implementing, this feature is used for me.
> @darful UniversalClient is also good solution, can you speak in detail why `UniversalClient` is better than a `Cmdable` interface? Usually, golang like interface more than a specific implement.

@vincenthcui `UniversalClient` is an interface and contains the `Cmdable` interface, see [here](https://github.com/go-redis/redis/blob/master/universal.go#L174).  The `UniversalClient` interface is a superset of all Redis client implementations in `go-redis` ([FailoverClient](https://github.com/go-redis/redis/blob/d4f01eda2825ce453eace6d8cbd2fe500714645d/sentinel.go#L159), [ClusterClient](https://github.com/go-redis/redis/blob/d4f01eda2825ce453eace6d8cbd2fe500714645d/cluster.go#L687), & [SimpleClient](https://github.com/go-redis/redis/blob/d4f01eda2825ce453eace6d8cbd2fe500714645d/redis.go#L558)) which means it can be used to represent all 3 clients.  I don't believe the is the case for `Cmdable`.

**Comment by vincenthcui** [comment]
@darful you are right, `UniversalClient` looks indeed more accurately than `Cmdalbe`, I change my mind.

**Comment by lpxxn** [comment]
UniversalClient is better, i will close this pr

**Comment by zcfh** [comment]
I rely on some other go Redis wrappers, which only expose `redis.Cmdable`. Is there a way to use Cmdable directly? It seems that this patch just changes `redis.Client` to `redis.Cmdable`

**Pull request closed without merging**
