### PR TITLE
feature: add auto extend

### PR DESCRIPTION
**Pull request by prOOrc**
Added the ability to automatically extend the lock

### CODE REVIEW

**Comment by sinceHYJ** [comment]
I really need this function, please the manager review as soon as possible

**Comment by v4rakh** [comment]
That would be so nice to have it in!

**Comment by xiaozhuang-a** [comment]
+1

**Comment by vmcqgo** [comment]
This feature would be nice, indeed. Looking through the PR I've noticed you are not handling the error returned by `ExtendContext(ctx context.Context) (bool, error)`, meaning that until the ticker ticks again, another instance can acquire the lock. Also, take into account that this function can return `false, nil` if the lock is already acquired by a different instance.

**Comment by prOOrc** [comment]
> This feature would be nice, indeed. Looking through the PR I've noticed you are not handling the error returned by `ExtendContext(ctx context.Context) (bool, error)`, meaning that until the ticker ticks again, another instance can acquire the lock. Also, take into account that this function can return `false, nil` if the lock is already acquired by a different instance.

You're right. I've fixed it.

**Pull request closed without merging**
