### PR TITLE
Allow for use of go-redis or redigo

### PR DESCRIPTION
**Pull request by btomasini**
I wanted to use this library but maintain my existing usage of go-redis in my project. Admittedly, it may only be an asthetic difference for my project.

This change allows the user of the library to choose which underlying redis library to use. The go modules file brings in both, but only the one used by the downstream project will actually be included.

Have a look. I understand if this is a change you would rather not include. I don't know what the demand for this would be, and it does increase the complexity of the project quite a bit.

The tests all pass.  Let me know your thoughts.

### CODE REVIEW

**Comment by btomasini** [comment]
This is a change to the API, so I guess a v2 would be called for for this change.

**Comment by btomasini** [comment]
Any interest in incorporating this?

**Comment by kamronbatman** [comment]
@hjr265, what is the status of a new major version? What were you thinking about adding? Maybe create an issue and someone can help fill out those requirements for that milestone?
Personally I would love to remove this dependency too, so I am interested in moving the ball forward.

**Comment by xmcqueen** [comment]
i'd like to see go-redis in here too

**Comment by mauricioabreu** [comment]
How can I help you to achieve it? I can help with code, tests, ideas, review.

**Comment by mauricioabreu** [comment]
@btomasini are you still interested on this? Maybe a fork? I can help rebasing and finishing whatever we need (code, docs, tests, etc)

**Comment by kamronbatman** [comment]
@mauricioabreu, I think @hjr265 has plans to include a version of this in the next major release. I wonder if we can help him with it!

**Comment by mauricioabreu** [comment]
@kamronbatman thank you! Let's wait for his answer.

**Comment by joshprzybyszewski-wf** [comment]
@hjr265 any update on this? I may also have an interest in using this repo if it supports go-redis

**Comment by marshallmcmullen** [comment]
@hjr265 Any update? I would also love to use this but I have a huge project already using `go-redis` and do not want to to have to port it over. But I also need `redsync` so this looks very needed for me too.

**Comment by hjr265** [comment]
@marshallmcmullen @joshprzybyszewski-wf @mauricioabreu @kamronbatman I have merged this and released as /v3. 

Thank you @btomasini for this pull request!

**Pull request merged**
